# Generated by Django 6.1 on 2026-08-13 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_zkproof_and_credential_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='zkproof',
            new_name='identity_zk_verific_1f5aca_idx',
            old_name='identity_zk_verreq_idx',
        ),
        migrations.AlterField(
            model_name='zkproof',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
