# Generated by Django 6.1 on 2026-10-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_rename_identity_zk_verreq_idx_identity_zk_verific_1f5aca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiablecredential',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='identity.identitydocument'),
        ),
    ]
