# Generated by Django 6.1 on 2026-10-07 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_add_challenge_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('VERIFICATION_REQUEST', 'Verification Request'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_DENIED', 'Verification Denied'), ('VERIFICATION_RESULT', 'Verification Result')], default='VERIFICATION_REQUEST', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('verification_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='verification.verificationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
