# Generated by Django 6.1 on 2026-08-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
